name: Playwright Tests
on: [pull_request, push]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      working-directory: ./web
      run: yarn
    - name: Install Playwright Browsers
      working-directory: ./web
      run: yarn playwright install --with-deps
    - name: Run Playwright tests
      working-directory: ./web
      run: yarn playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
