name: Web app lint
on: [push]

jobs:
  web-tsc:
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: 'web'
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: '**/yarn.lock'

      - name: Install dependencies
        run: yarn

      - name: Lint with tsc
        run: yarn tsc
